### ISSUE TITLE
Should the newer CC Version 4 License be used instead of v3?

### ISSUE THREAD

**Issue by wiktoriavh** [confcodeofconduct/confcodeofconduct.com#178]
When you visit the currently linked license page, there is a notice about version 4 being a more robust and overall better version of the license. Should it be considered to update the license to version 4? Version 3 ist not ported, while version 4 is.

Version 3: https://creativecommons.org/licenses/by/3.0/deed.en
Version 4: https://creativecommons.org/licenses/by/4.0/deed.en

The text on both of these is the same, but the actual legal text has differences.

Legal v3: https://creativecommons.org/licenses/by/3.0/legalcode.en
Legal v4: https://creativecommons.org/licenses/by/4.0/legalcode.en

Here is an overview of what changed: https://creativecommons.org/version4/

**Comment by MattiSG** [comment]
Thanks @wiktoriavh for pointing this ou!
Since we do not request contributors to transfer their copyright to any specific rights holder, as I understand it, we can't bump the license on behalf of those who contributed content under a specific license. The ways to handle this situation would thus be to:

1. Reach out to every past contributor and ask for their agreement to re-license under CC4.
2. For new translations contributed, publish under CC4, so that the content is progressively updated.
3. Consider that no author will care that their work contributed under CC3 is re-licensed under CC4 and make the change by default on their behalf, allowing a revert if they end up disagreeing.

I believe option 2 is most compliant and realistic, and do not see any urgency in updating the license for existing content. We would thus simply update the license number for new translations.

Does that sound like a relevant approach to you? 🙂

**Comment by wiktoriavh** [comment]
Hey @MattiSG,

number 2 sounds like the best approach. 🙂

It might be worth enabling Releases, so it is possible to version the respository. This way it is more clear which release uses which license. Also great for future licensing changes, I would assume.

**Comment by MattiSG** [comment]
Thank you for your suggestion! Considering that this is just a live website, unless you see a clear use case for pinpointing specific versions of the entire website, I believe that the versioning system of Git itself will be sufficient 🙂

I will proceed with closing this issue since we agreed not to bump the license version for the entire repository now.

Thank you again for your contributions, notably to the German translation!
