### ISSUE TITLE
No "sexualised clothing/uniforms/costumes"?

### ISSUE THREAD

**Issue by umazalakain** [confcodeofconduct/confcodeofconduct.com#69]
We recently adopted this CoC for our Python Glasgow meetings. [As you can see](https://mail.python.org/pipermail/glasgow/2015-February/000131.html), a bit of discussion went on around this statement that says that `Booth staff (including volunteers) should not use sexualised clothing/uniforms/costumes, or otherwise create a sexualized environment.`

My arguments to be against such a statement are:
- `Sexualized` clothing is very ill defined. What dictates what's appropriate non-sexualized clothing greatly depends on cultural, religious and geographical backgrounds. People in Thailand, Colombia, UK, Madagascar or Arab Emirates all have a very different perception of what sexualized clothing is.
- By definition, _clothing is not sexualized_. Sexualized is the brain after the eyes that looks at the clothing.
- Sexuality is part of every individual, taking away someone's sexuality is taking away a piece of them.
- AFAIK, this statement tries to solve the "booth babes" issue. This issue exists because companies make use of certain aspects of people to promote themselves. Why are we limiting individual freedom to solve an issue created by companies? Company freedoms should be limited instead for example banning any use of an individual's `gender, age, sexual orientation, disability, physical appearance, body size, race, religion` for self promotion.

**Comment by janl** [comment]
> Sexualized clothing is very ill defined.

Events should use a definition that works in the location of the event. This policy isn’t meant verbatim for the whole world.

> By definition, clothing is not sexualized. Sexualized is the brain after the eyes that looks at the clothing.

This is semantic nitpickery that derails from the issue at hand.

> Sexuality is part of every individual

So is poo, yet we confine it to the place where it is safe to dispose.

> Company freedoms should be limited instead for example banning any use of an individual's gender, age, sexual orientation, disability, physical appearance, body size, race, religion for self promotion

If you feel this wording reflects better what you believe to be right, go for it. I read this to mean the same thing as what is in the original.

**Comment by unaizalakain** [comment]
Events are usually attended by  people with very different cultural backgrounds and each cultural background even have its subcultures that depend usually on social class. If an event restricts what it considers as appropriate clothing to  the clothing of only one of these, it is actually being uninviting to people from others.

 I do also not consider my statement as semantic nitpickery, what I meant is that the sexualization of the clothing isn't exercised by the individual who is wearing the clothes.

I speak about sexuality, not about sex. Sexuality plays a big part in how someone views their own person. I don't want to leave a piece of my personality that doesn't hurt anyone at home because of the misuse of sexual attraction by some companies which I despise.

My point with all this is exactly that it's not the same denying individuals their right to wear whatever they consider appropriate and denying companies the use of some aspects of their staff to promote themselves.

I'll try to write a PR addressing this issue but I would highly appreciate some help, I'm not a native English speaker.

**Comment by janl** [comment]
I don’t see anything that needs changing.

**Comment by unaizalakain** [comment]
>I don’t see anything that needs changing.
Could you elaborate on that please?

-- 
unai

**Comment by remy** [comment]
@unaizalakain I think @janl already explained with:

> Events should use a definition that works in the location of the event. This policy isn’t meant verbatim for the whole world.

This is absolutely spot on. This CoC works out of the box for *some* events, and not for others. It's a great starting point, and your event has made an adaption which is spot on the right thing to do.

**Comment by unaizalakain** [comment]
>> Events should use a definition that works in the location of the 
>> event. This policy isn’t meant verbatim for the whole world.
>
>This is absolutely spot on. This CoC works out of the box for *some* 
>events, and not for others. It's a great starting point, and your event 
>has made an adaption which is spot on the right thing to do.

I have trouble seeing the validity of such an argument when the exact 
purpose of this CoC is to provide the community with *sensible 
defaults*. A default that states that only some arbitrarily decided 
clothing is appropriate while claiming that no discrimination is 
tolerated because of appearance is contradictory at least.

**Comment by sh1989** [comment]
The document is a reference template - however, there's definitely an argument to be made that the main site ought to emphasize that this is a starting point, that conference organizers really ought to discuss the document and make any changes that they see necessary for their conference.

It's very common to see a straight-copy-paste of the document - but of course it's difficult to know what organizers did or did not do when they made that decision.

I think that point is separate from whether the text as provided constitutes a "sensible default". But by being more explicit about it being just that, we can encourage a pause for thought. As with #100 - it's worth being clear about what the document is and isn't.

**Comment by asdlkjqwepoi** [comment]
I'd like to re-open up this discussion as I think @unaizalakain has a valid point here. I'd like to share an anecdote if I could.

A little while ago my wife started a new job. She was wearing professional clothing no different to what she had worn at previous similar jobs. Her manager pulled her aside one day to tell her that her attire was unprofessional and that she had to cover up more. Apparently a senior male co-worker was so offended (or distracted) by her body that he decided he had the right to dictate what she could or could not wear to work.

My wife was absolutely humiliated by the whole experience. In one single meeting she had been made to feel unprofessional and therefore unfit to do her job, she felt unfairly judged by her coworkers, and perhaps most importantly she no longer felt safe at work due to the unwanted sexual attention.

I feel this last point is what @unaizalakain may have been getting at by this statement:

> By definition, clothing is not sexualized. Sexualized is the brain after the eyes that looks at the clothing.

My wife was not wearing sexualized clothing. It was the people at her workplace who chose to sexualize what she was wearing, and then made it her problem rather than their own.

To make matters worse, the changes she was forced to make made her much less comfortable (physically) while working. Of course this was only the beginning of a series of harassment that forced her leave that employer.

---

I think I can see where the code of conduct is coming from with this language. Organisations of course should not be using sex as a promotional tool at a conference, including 'booth babes'. I applaud how you are making conferences a safer place by getting rid of such practices. My concern is that the language currently used in this code of conduct puts people (especially women) at risk of the sort of experience my wife was forced to endure. I would hate to think that a conference attendee or organiser could approach someone who is just trying to do their job, and tell them "Your skirt is too short and your neckline is too low - you are not welcome here."

Would you be willing to consider a pull request on this issue?

**Comment by MattiSG** [comment]
> Would you be willing to consider a pull request on this issue?

I don't know who exactly your question is targeting. I don't think it is up to the gatekeeper(s) of this repo to decide on the contents of the CoC itself. I consider myself as a servant to the community here, simply making sure translations are up to date and contributions are not ignored.

I created the `redaction-committee` tag in the prospect that at some point we will assemble a team or a process to define more precisely the content and its evolutions. Lacking that, I believe your best course of action is to actually open that pull request and get people to back it up and debate around it 🙂 if a consensus large enough emerges, I will be happy to merge the changes.
