### ISSUE TITLE
More prominent link to GF wiki

### ISSUE THREAD

**Issue by aurynn** [confcodeofconduct/confcodeofconduct.com#75]
Since the text of the CoC is a bit out of date compared to the text on the [Geek Feminism Wiki](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy), I'd like to see a much more prominent link or redirect to the GF wiki's CoC entry.

**Comment by remy** [comment]
Happy to take a PR updating the css (I'm happy to help where possible if you have specific ideas).

Reading the link, a redirect wouldn't work as many point directly to this resource (rather than forking or taking it as a starting point), and the link you posted is a template (with things like "this is an example code of conduct" etc).

Just as background: this copy of the CoC isn't intended as a copy of the Ada Initiative one, but the original copy was definitely taken from jsconf, which in turn credits the Ada Initiative.

**Comment by remy** [comment]
I'm wary that my last reply might come off a bit dismissive. Its not intended if it did come over that way! 

My point about the redirect is that we can't just blanket redirect, it wouldn't work as a live usable CoC.

A more prominent link to the latest Ada copy makes sense, and equally I might be worth looking at what's out of date. Again, this repo isn't a copy, but if there's changes that this repo should have, then the repo should have them!

Cheers and thanks for raising the issue.

**Comment by aurynn** [comment]
I don't think it came off as dismissive, just noting that these things are Hard :) The lack of trans-specific language on the CoC was what concerned me, compared to the GF variant. As your CoC is becoming more commonly used, not having that was of importance to me.

**Comment by MattiSG** [comment]
Hi @aurynn! The CoC contents might have changed a bit since two years ago, are you still concerned with the lack of trans-specific language with the current version? 🙂

**Comment by aurynn** [comment]
Hi @MattiSG;

Yep, that looks a lot better. It'd also suggest changing "organisers _may_ take any action" to "organisers _will_ take any action". And I'll open a separate issue to bring up building a resolution strategy. :)

Thanks!
