### ISSUE TITLE
readability

### ISSUE THREAD

**Issue by iamstarkov** [confcodeofconduct/confcodeofconduct.com#96]
From my perspective readability can be better from two points of view: fontface and justify.

Font is very hard to read for me:
![screen shot 2015-08-04 at 16 39 47](https://cloud.githubusercontent.com/assets/559321/9063401/75c8ba78-3ac7-11e5-8ecf-32f5affe492a.png)

Justified content create [space rivers](http://www.wikiwand.com/en/River_%28typography%29):
![pasted_image_at_2015_08_04_16_21](https://cloud.githubusercontent.com/assets/559321/9063425/99981804-3ac7-11e5-97e8-eb5eee30faa1.png)

Also prob readability can be better if text column make more narrow nearly 60-80 chars in the line

**Comment by remy** [comment]
cmd + is your friend, I've intentionally supported this (I personally run most sites at 125%).

**Comment by iamstarkov** [comment]
thank you for response, but it’s not about size at all. it’s about space rivers, weak contrast for this typeface and very wide column

**Comment by iamstarkov** [comment]
font size is very-very acceptable

**Comment by filipovskii** [comment]
What @iamstarkov is referring to is this extra space between words, that make it harder to read:

![99981804-3ac7-11e5-97e8-eb5eee30faa1](https://cloud.githubusercontent.com/assets/610717/9071325/0cf6f1ee-3af5-11e5-8e6e-d55a0adad464.png)

This is a common issue in typography. In this case it's caused by `text-align: justify`.
